orders/urls.py
from django.urls import path 
from .views import add_to_cart,order_list,checkout,process_payment,payment_success,payment_failed

urlpatterns = [
    path('' , order_list),
    path('checkout/' , checkout),
    path('checkout/process-payment' , process_payment),
    path('checkout/payment/success' , payment_success),
    path('checkout/payment/failed' , payment_failed),
    
    path('add-to-cart', add_to_cart),
]

products/urls.py
from django.urls import path
from .views import ProductList,ProductDetail,BrandList,BrandDetail,add_product_review ,debug

from .api import  ProductListAPI , ProductDetailAPI , BrandListAPI , BrandDetailApi


urlpatterns =[
    path('' , ProductList.as_view()),
    path('debug' ,debug),
    path('brands' , BrandList.as_view()),
    path('<slug:slug>', ProductDetail.as_view()),
    path('<slug:slug>/add-review', add_product_review),
    path('brands/<slug:slug>' , BrandDetail.as_view()),


    # path('api/list', product_list_api),
    path('api/list', ProductListAPI.as_view(),name='product list api'),
    path('api/list/<int:pk>', ProductDetailAPI.as_view(),name='product detail api'),
    path('api/brands/', BrandListAPI.as_view(),),
    path('api/brands/<int:pk>',  BrandDetailApi.as_view(),),
]

project/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

from django.urls import re_path
from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi



schema_view = get_schema_view(
   openapi.Info(
      title="Amazon Clone API",
      default_version='v1',
      description="All The Endpoints for Amazon Clone API",
      terms_of_service="https://www.google.com/policies/terms/",
      contact=openapi.Contact(email="contact@snippets.local"),
      license=openapi.License(name="BSD License"),
   ),
   public=True,
   permission_classes=(permissions.AllowAny,),
)





urlpatterns = [
    path('admin/', admin.site.urls),
    path('products/', include('products.urls')),
    path('orders/', include('orders.urls')),
    path('', include('settings.urls')),
    
    path("__debug__/", include("debug_toolbar.urls")),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/models.py
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.contrib.auth.models import User
from django.utils.text import slugify

FLAG_CHOICES = (
    ('New','New'),
    ('Sale','Sale'),
    ('Feature','Feature'),
)


class Product(models.Model):
    name = models.CharField(_('Product Name'), max_length=120)
    image = models.ImageField(_('Image'),upload_to='products')
    price = models.FloatField(_('Price'))
    subtitle = models.TextField(_('Subtittle'),max_length=500)
    description = models.TextField(_('description'),max_length=50000)    
    sku = models.IntegerField(_('SKU'))
    video = models.URLField(_('Video'),null=True,blank=True)
    quantity = models.IntegerField(_('Quantity'))
    flag = models.CharField(_('Flag') ,max_length=10, choices=FLAG_CHOICES)
    brand = models.ForeignKey('Brand',related_name = 'product_brand',on_delete=models.SET_NULL, null=True)
    slug= models.SlugField(null=True,blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)



class ProductImages(models.Model):
    product=models.ForeignKey(Product, related_name= 'product_images', on_delete=models.CASCADE)
    image= models.ImageField(upload_to='product_images')



class Brand(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='brands')
    slug= models.SlugField(null=True,blank=True)


    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Brand, self).save(*args, **kwargs)

    def __str__(self):
        return self.name



class Review(models.Model):
   user = models.ForeignKey(User,related_name='review_user',on_delete=models.SET_NULL, null=True, blank=True)
   product = models.ForeignKey(Product,related_name = 'review_product',on_delete=models.CASCADE)
   review = models.TextField(max_length=300)
   rate = models.IntegerField()
   create_at = models.DateTimeField(default=timezone.now)


   def __str__(self):
       return str(self.user)

products/forms.py
from  django import forms
from .models import Review


class ReviewForm(forms.ModelForm):
    class  Meta:
        model = Review
        fields = ['review','rate']

products/views.py
from django.shortcuts import render ,redirect
from django.views.generic import ListView , DetailView 

from django.db.models import Q 

from .models import Product , Brand , Review , ProductImages
from .forms import ReviewForm

def  debug(requset):
    # data = Product.objects.all()

    # data = Product.objects.filter(price__gt=98)
    # data = Product.objects.filter(price__gte=98)
    # data = Product.objects.filter(price__lt=22)
    # data = Product.objects.filter(price__lte=22)
    # data = Product.objects.filter(price__range=(21,22))

    # data = Product.objects.filter(name__contains='Jeffrey')
    # data = Product.objects.filter(name__startswith='Jeffrey')
    # data = Product.objects.filter(name__endswith='Garcia')

    # data = Product.objects.filter(name__contains='Jeffrey',price__gt=50)
    
    # data = Product.objects.filter(
    #     Q(name__contains='Jeffrey') &
    #     Q(price__gt=90)
    #       )

    # data = Product.objects.filter(
    #     Q(name__contains='Jeffrey') |
    #     Q(price__gt=50)
    #       )
    
    # data = Product.objects.filter(
    #     Q(name__contains='Jeffrey') |
    #     ~Q(price__gt=22)
    #       )

    # data = Product.objects.order_by('price')
    # data = Product.objects.order_by('-price')
    
    # data = Product.objects.all()[:5]
    # data = Product.objects.earliest('price')
    # data = Product.objects.latest('price')
    # print(data)

    # django queries are lazy
    # data = Product.objects.filter(name__contains='Jeffrey').order_by('-price')      # merg queries (SQl)

    # data = Product.objects.filter(name__contains='Jeffrey')
    # data = data.order_by('-price')

    # data = Product.objects.all()
    # data = Product.objects.values('name')
    # data = Product.objects.values_list('name')
    # data = Product.objects.only('name')
    data = Product.objects.defer('slug','description')

    return render(requset,'products/debug.html',{'data':data})


class ProductList(ListView):
    model = Product
    paginate_by = 50




class ProductDetail(DetailView):
    model = Product


    def  get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["product_images"] = ProductImages.objects.filter(product=self.get_object())
        context["product_review"] = Review.objects.filter(product=self.get_object())
        return context




class BrandList(ListView):
    model = Brand
    paginate_by = 20


class BrandDetail(ListView):
    model = Product
    template_name = 'products/brand_detail.html' 
    paginate_by = 20

    def get_queryset(self):
        brand = Brand.objects.get(slug=self.kwargs['slug'])
        queryset = super().get_queryset()
        queryset = queryset.filter(brand=brand)
        return queryset 
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context ['brand'] = Brand.objects.get(slug=self.kwargs['slug'])
        return context
    

def add_product_review(request,slug):
    product = Product.objects.get(slug=slug)

    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.user =  request.user
            myform.product = product
            myform.save()

            return redirect(f'/products/{slug}')

products/templates/products/brand_detail.html
{% extends 'base.html' %}
{% load static %}


{% block css %}
    <link rel="stylesheet" href="{% static 'en/css/brand-single.css' %}" >
{% endblock css %}


{% block body %}
        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>Brand Single</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item"><a href="brand-list.html">brand-list</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-single</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                  BRAND SINGLE PART START
        =======================================-->
        <div class="brand-single">
            <a href="#"><img src="{{brand.image.url}}" alt="brand"></a>
            <a href="#"><h3>{{brand}}</h3></a>
            <ul>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star active"></li>
                <li class="fas fa-star"></li>
                <li class="total">(163 ratings)</li>
            </ul>
            <p>(45 items)</p>
        </div>
        <!--=====================================
                  BRAND SINGLE PART END
        =======================================-->


        <!--=====================================
                    SHOP PART START
        =======================================-->
        <section class="inner-section shop-part">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select">
                                    <option selected>default</option>
                                    <option value="3">trending</option>
                                    <option value="1">featured</option>
                                    <option value="2">recommend</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-5">
                    {% for item in product_list %}
                    <div class="col">
                        <div class="product-card">
                            <div class="product-media">
                                <div class="product-label">
                                    <label class="label-text new">{{item.flag}}</label>
                                </div>
                                <button class="product-wish wish">
                                    <i class="fas fa-heart"></i>
                                </button>
                                <a class="product-image" href="product-video.html">
                                    <img src="{{item.image.url}}" alt="product">
                                </a>
                                <div class="product-widget">
                                    <a title="Product Compare" href="compare.html" class="fas fa-random"></a>
                                    <a title="Product Video" href="https://youtu.be/9xzcVxSBbG8" class="venobox fas fa-play" data-autoplay="true" data-vbtype="video"></a>
                                    <a title="Product View" href="#" class="fas fa-eye" data-bs-toggle="modal" data-bs-target="#product-view"></a>
                                </div>
                            </div>
                            <div class="product-content">
                                <div class="product-rating">
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="icofont-star"></i>
                                    <a href="product-video.html">(3)</a>
                                </div>
                                <h6 class="product-name">
                                    <a href="/products/{{item.slug}}">{{item}}</a>
                                </h6>
                                <h6 class="product-price">
                                    <span>${{item.price}}</span>
                                </h6>
                                <button class="product-add" title="Add to Cart">
                                    <i class="fas fa-shopping-basket"></i>
                                    <span>add</span>
                                </button>
                                <div class="product-action">
                                    <button class="action-minus" title="Quantity Minus"><i class="icofont-minus"></i></button>
                                    <input class="action-input" title="Quantity Number" type="text" name="quantity" value="1">
                                    <button class="action-plus" title="Quantity Plus"><i class="icofont-plus"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                        {% if is_paginated %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="bottom-paginate">
                                    <p class="page-info">Showing 12 of 60 Results</p>
                                    <ul class="pagination">
    
                                        {% if page_obj.has_previous %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{page_obj.previos_page_number}}">
                                                    <i class="fas fa-long-arrow-alt-left"></i>
                                                </a>
                                            </li>
                                        {% endif %}
    
                                        
                                        
                                        {% for i in paginator.page_range %}
                                            {% if page_obj.number == i %}
                                                <li class="page-item"><a class="page-link active" href="#">{{i}}</a></li>
                                            {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
                                                <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                                            {% endif %}
    
                                        {% endfor %}
    
    
    
    
                                        {% if page_obj.has_next %}
                                            <li class="page-item">
                                                <a class="page-link" href="?page={{page_obj.next_page_number}}">
                                                    <i class="fas fa-long-arrow-alt-right"></i>
                                                </a>
                                            </li>
                                        {% endif %}
    
                                    </ul>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </section>
        <!--=====================================
                    SHOP PART END
        =======================================-->
        {% endblock body %}

products/templates/products/brand_list.html
{% extends 'base.html' %}
{% block body %}

        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>brand list</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">brand-list</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    BRAND LIST PART START
        =======================================-->
        <section class="inner-section">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select isotope-select">
                                    <option value="*">show all</option>
                                    <option value=".vegetables">vegetables</option>
                                    <option value=".fruits">fruits</option>
                                    <option value=".drinks">drinks</option>
                                    <option value=".fishes">fishes</option>
                                    <option value=".meats">meats</option>
                                </select>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-4 row-cols-xl-5 isotope-items">
                    {% for item in object_list %}
                    <div class="col all vegetables">
                        <div class="brand-wrap">
                            <div class="brand-media">
                                <img src="{{item.image.url}}" alt="brand">
                                <div class="brand-overlay">
                                    <a href="/products/brands/{{item.slug}}"><i class="fas fa-link"></i></a>
                                </div>
                            </div>
                            <div class="brand-meta">
                                <h4>{{item}}</h4>
                                <p>(45 items)</p>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                        {% if is_paginated %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="bottom-paginate">
                                <p class="page-info">Showing 12 of 60 Results</p>
                                <ul class="pagination">

                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{page_obj.previos_page_number}}">
                                                <i class="fas fa-long-arrow-alt-left"></i>
                                            </a>
                                        </li>
                                    {% endif %}

                                    
                                    
                                    {% for i in paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class="page-item"><a class="page-link active" href="#">{{i}}</a></li>
                                        {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
                                            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                                        {% endif %}

                                    {% endfor %}




                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{page_obj.next_page_number}}">
                                                <i class="fas fa-long-arrow-alt-right"></i>
                                            </a>
                                        </li>
                                    {% endif %}

                                </ul>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </section>
        <!--=====================================
                    BRAND LIST PART END
        =======================================-->
        {% endblock body %}

products/templates/products/debug.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>Welcome</h1>

<ul>
    {% for object in data %}
    <li>{{object}}</li>
    {% endfor %}
</ul>
</body>
</html>

products/templates/products/product_list.html
{% extends 'base.html' %}
{% block body %}


        <!--=====================================
                    BANNER PART START
        =======================================-->
        <section class="inner-section single-banner" style="background: url(images/single-banner.jpg) no-repeat center;">
            <div class="container">
                <h2>Shop 5 Column</h2>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                    <li class="breadcrumb-item active" aria-current="page">shop-5column</li>
                </ol>
            </div>
        </section>
        <!--=====================================
                    BANNER PART END
        =======================================-->


        <!--=====================================
                    SHOP PART START
        =======================================-->
        <section class="inner-section shop-part">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <div class="top-filter">
                            <div class="filter-show">
                                <label class="filter-label">Show :</label>
                                <select class="form-select filter-select">
                                    <option value="1">12</option>
                                    <option value="2">24</option>
                                    <option value="3">36</option>
                                </select>
                            </div>
                            <div class="filter-short">
                                <label class="filter-label">Short by :</label>
                                <select class="form-select filter-select">
                                    <option selected>default</option>
                                    <option value="3">trending</option>
                                    <option value="1">featured</option>
                                    <option value="2">recommend</option>
                                </select>
                            </div>
                            <div class="filter-action">
                                <a href="shop-3column.html" title="Three Column"><i class="fas fa-th"></i></a>
                                <a href="shop-2column.html" title="Two Column"><i class="fas fa-th-large"></i></a>
                                <a href="shop-1column.html" title="One Column"><i class="fas fa-th-list"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="row row-cols-2 row-cols-md-3 row-cols-lg-3 row-cols-xl-5">
                    {% for item in product_list %}
                    <div class="col">
                        <div class="product-card">
                            <div class="product-media">
                                <div class="product-label">
                                    <label class="label-text new">{{item.flag}}</label>
                                </div>
                                <button class="product-wish wish">
                                    <i class="fas fa-heart"></i>
                                </button>
                                <a class="product-image" href="product-video.html">
                                    <img src="{{item.image.url}}" alt="product">
                                </a>
                                <div class="product-widget">
                                    <a title="Product Compare" href="compare.html" class="fas fa-random"></a>
                                    <a title="Product Video" href="https://youtu.be/9xzcVxSBbG8" class="venobox fas fa-play" data-autoplay="true" data-vbtype="video"></a>
                                    <a title="Product View" href="#" class="fas fa-eye" data-bs-toggle="modal" data-bs-target="#product-view"></a>
                                </div>
                            </div>
                            <div class="product-content">
                                <div class="product-rating">
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="active icofont-star"></i>
                                    <i class="icofont-star"></i>
                                    <a href="product-video.html">(3)</a>
                                </div>
                                <h6 class="product-name">
                                    <a href="/products/{{item.slug}}">{{item.name}}</a>
                                </h6>
                                <h6 class="product-price">
                                    <span>${{item.price}}</span>
                                </h6>
                                <button class="product-add" title="Add to Cart">
                                    <i class="fas fa-shopping-basket"></i>
                                    <span>add</span>
                                </button>
                                <div class="product-action">
                                    <button class="action-minus" title="Quantity Minus"><i class="icofont-minus"></i></button>
                                    <input class="action-input" title="Quantity Number" type="text" name="quantity" value="1">
                                    <button class="action-plus" title="Quantity Plus"><i class="icofont-plus"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% if is_paginated %}
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="bottom-paginate">
                                <p class="page-info">Showing 12 of 60 Results</p>
                                <ul class="pagination">

                                    {% if page_obj.has_previous %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{page_obj.previos_page_number}}">
                                                <i class="fas fa-long-arrow-alt-left"></i>
                                            </a>
                                        </li>
                                    {% endif %}

                                    
                                    
                                    {% for i in paginator.page_range %}
                                        {% if page_obj.number == i %}
                                            <li class="page-item"><a class="page-link active" href="#">{{i}}</a></li>
                                        {% elif i > page_obj.number|add:'-4' and i < page_obj.number|add:'4' %}
                                            <li class="page-item"><a class="page-link" href="?page={{i}}">{{i}}</a></li>
                                        {% endif %}

                                    {% endfor %}




                                    {% if page_obj.has_next %}
                                        <li class="page-item">
                                            <a class="page-link" href="?page={{page_obj.next_page_number}}">
                                                <i class="fas fa-long-arrow-alt-right"></i>
                                            </a>
                                        </li>
                                    {% endif %}

                                </ul>
                            </div>
                        </div>
                    </div>
                {% endif %}
            </div>
        </section>
        <!--=====================================
                    SHOP PART END
        =======================================-->
        
{% endblock body %}
        

  